# Create a comment on a PR with text from a file
# Inputs file-name
name: PR comment
on: 
    workflow_call:
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
            name: coverage-${{ github.sha }}
      - name: Read coverage and set output
        id: coverageOutput
        run: |
            output=`cat lcov-report/index.html`
            echo "coverage=$output" >> $GITHUB_OUTPUT
      - name: Comment PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ steps.coverageOutput.outputs.coverage }}'
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
